### ISSUE TITLE
def can_be_created_in_a_block spec issue

### ISSUE THREAD

**Issue by leiaj** [learn-co-curriculum/activerecord-crud#34]
def can_be_created_in_a_block
  Movie.create do |m|
   __
  end
end

-----

In this lab, the spec asks for us to create a new instance of movie with a block with the #create method. 

We figured out that unless you hardcore what the test is passing:

  it 'can be created in a block' do
        movie = can_be_created_in_a_block

        expect(Movie.last).to eq(movie)
        expect(Movie.last.title).to eq("Home Alone")
        expect(Movie.last.release_date).to eq(1990)
      end
    
--
There is no way to pass the spec. It is specifically asks you to solve this problem with one line of code, but based on the fact there are no arguments it is impossible. 

--

We have confirmation from JJ that this is true.

:) <3

**Comment by leiaj** [comment]
ps it has to look like this to pass:

def can_be_created_in_a_block
  Movie.create do |m|
    m.title = "Home Alone"
    m.release_date = 1990
  end
end

**Comment by sgharms** [comment]
Hi there, @leiaj I don't like this whole hard-coding business that you and @will-sauer have pointed to. I'm going to make the code require some arguments passing so that we're not having to code in the misadventures of Kevin McAllister in order to get the test to pass. It'll be merged in the next few minutes.
