### ISSUE TITLE
the syntax error

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/activerecord-crud#51]
I got a notification that the starter code in this lab was fixed so as not to throw a syntax error anymore. However, a student just popped up on AAQ with the same issue. The underscores between the {} are causing it.

**Comment by curiositypaths** [comment]
Hello @d-d-d-dalia,

Thank you for reporting the issue. The `specs` for the [canonical repository](https://github.com/learn-co-curriculum/activerecord-crud) (Used to maintain the curriculum) and for the [deployed version](https://github.com/learn-co-students/activerecord-crud-v-000) (Used to deploy curriculum to FSWD online students) seem to work. Perhaps the student forked the repository prior to our update.

If the issue happens again let's capture the student `repository url` in order to reproduce the issue.

As always thank you for contributing!
